language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install coveralls
script:
  - python -m unittest
after_success:
  - coverage run --source=pa193mnemonicslytherin python -m unittest
  - coveralls
