language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install coveralls
script:
  - python setup.py test
after_success:
  - coverage run --source=PA193_mnemonic_Slytherin setup.py test
  - coveralls
